// https://www.random.org/faq/#S1
const Data = [
  {
    question: `Will RANDOM.ORG be around in X years?`,
    answer: `Probably, depending on your value for X. We have run the service since 1998 with no real interruptions, and it is more popular than ever.`,
  },
  {
    question: `Does RANDOM.ORG perform custom jobs that require randomness?`,
    answer: `Yes. Perhaps you need more numbers than it's possible to get via the web forms, or perhaps you need them in a format that isn't supported. In those cases, we can set up a custom job for you to supply the numbers. We also act as independent observers for drawings and competitions via the Third-Party Draw Service.`,
  },
  {
    question: `I seem not to be receiving emails from RANDOM.ORG. What is wrong?`,
    answer: `RANDOM.ORG will send email to you when you register for a Premium Account or if you have forgotten your password. It can also email you if you use the Premium Generator or the Third-Party Draw Service. If you have problems receiving any of these emails, please check your spam filter configuration. It should be set to accept emails from notifications@random.org. If you are still experiencing problems, please let us know.`,
  },
  {
    question: `How can you be sure the numbers are really random?`,
    answer: `Oddly enough, it is theoretically impossible to prove that a random number generator is really random. Rather, you analyse an increasing amount of numbers produced by a given generator, and depending on the results, your confidence in the generator increases (or decreases, as the case may be). This is explained in more detail on my Statistical Analysis page, which also contains two studies of the numbers generated by RANDOM.ORG, both of which concluded that the numbers are sound. In addition, the continually updated Real-Time Statistics page gives you an indication of the quality of the numbers produced over time.`,
  },
  {
    question: `Have the numbers been certified by an independent third party?`,
    answer: `The numbers produced by RANDOM.ORG have been evaluated by eCOGRA, which is a non-profit regulatory body that acts as the independent standards authority of the online gaming industry. For a typical gambling site, eCOGRA will oversee many aspects of its operation, including financial aspects, such as payout percentages. RANDOM.ORG is not a gambling site, so in our case, eCOGRA only evaluated the quality of the random numbers. They found that RANDOM.ORG consistently produced random numbers across scaling intervals and issued a certificate with their conclusion: ecogra-2009-06-25.pdf (1 page, 52 Kb)
    The numbers and software have also been evaluated by TST Global (part of Gaming Labs International) who in 2011 examined the generator for use in games hosted on Malta. TST's report stated that RANDOM.ORG ‘distributes numbers with sufficient non-predictability and fair distribution to particular outcomes’ and concluded that it ‘complies with the requirements of the applicable Technical Standard in the jurisdiction of Malta as regulated by The Malta Gaming Authority (MGA).’`,
  },
];
export default Data;
